services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/devops-dashboard
      CLIENT_ORIGIN: http://localhost:8080
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo-data:
