# Multi-stage Docker build for DevOps Hub
# Stage 1: Builder - compiles frontend and prepares backend
# Stage 2: Production - lean runtime image

# ============================================================================
# STAGE 1: BUILDER - Install all dependencies, build frontend, prepare apps
# ============================================================================
FROM node:20-alpine AS builder

LABEL stage=builder

WORKDIR /build

# Copy all package files for dependency resolution
COPY package*.json ./
COPY frontend/package*.json ./frontend/
COPY backend/package*.json ./backend/

# Install ALL dependencies (including devDependencies for build tools)
# This is needed for Vite, ESLint, TypeScript, and other build-time tools
RUN npm ci

# Copy entire project source into builder
COPY . .

# Build frontend with Vite
# This generates frontend/dist with optimized HTML, CSS, JS bundles
# Vite performs minification, tree-shaking, and code splitting automatically
RUN npm run build:frontend

# Verify frontend dist was created successfully
RUN test -d frontend/dist && test -f frontend/dist/index.html || \
    (echo "ERROR: Frontend build failed - frontend/dist/index.html not found" && exit 1)

# Show build artifacts size for verification
RUN echo "✅ Frontend build complete:" && \
    ls -lah frontend/dist/ && \
    du -sh frontend/dist/

# ============================================================================
# STAGE 2: PRODUCTION - Lean runtime with only production dependencies
# ============================================================================
FROM node:20-alpine

LABEL stage=production
LABEL description="DevOps Hub - Production Build"
LABEL version="1.0.0"

# Set production environment flags
ENV NODE_ENV=production \
    NPM_CONFIG_PRODUCTION=true \
    NODE_OPTIONS="--max-old-space-size=512"

WORKDIR /app

# Copy package files for dependency installation
COPY package*.json ./
COPY backend/package*.json ./backend/

# Install ONLY production dependencies
# Skip devDependencies (Vite, ESLint, TypeScript, etc.)
# npm ci is preferred over npm install for reproducible builds
RUN npm ci --omit=dev && \
    npm cache clean --force

# Copy built frontend from builder stage
# This includes all optimized HTML, CSS, JS bundles generated by Vite
COPY --from=builder /build/frontend/dist ./frontend/dist

# Copy backend source code
# Express server will serve frontend/dist as static files from this directory
COPY backend/ ./backend/

# Create non-root user for security
RUN addgroup -S devops && \
    adduser -S devops -G devops && \
    chown -R devops:devops /app

USER devops

# Only expose production port
EXPOSE 5000

# Health check: verify server is responsive
# Checks /api/health endpoint every 30 seconds
# Timeout: 10 seconds for response
# Start period: 40 seconds grace period after container start
# Retries: 3 consecutive failures triggers restart
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
  CMD node -e "require('http').get('http://localhost:5000/api/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})" || exit 1

# Start backend Express server which serves frontend and API
# npm start runs: node backend/src/server.js
# This starts Express on 0.0.0.0:5000 and serves:
#   - Frontend HTML+assets at GET /
#   - REST API at GET /api/*
#   - WebSocket at ws://
CMD ["npm", "start"]