import mongoose from "mongoose";

const deploymentSchema = new mongoose.Schema(
  {
    userId: {
      type: String,
      required: true,
    },
    pipelineId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Pipeline",
    },
    buildNumber: Number,
    commitSha: String,
    projectId: {
      type: String,
      index: true,
    },
    deploymentId: {
      type: String,
      unique: true,
      sparse: true,
    },
    repository: String,
    owner: String,
    branch: String,
    workspacePath: String,
    deploymentStage: {
      type: String,
      enum: [
        "PREPARED",
        "IMAGE_BUILT",
        "TESTED",
        "PUSHED_TO_REGISTRY",
        "DEPLOYED",
        "REPOSITORY_CONNECTED",
        "ANALYZED",
        "READINESS_REPORTED",
        "DEPLOYMENT_FILES_GENERATED",
        "DOCKER_HUB_CONNECTED",
        "EC2_CONNECTED",
        "JENKINS_CONNECTED",
        "JENKINS_PIPELINE_GENERATED",
        "CICD_GENERATED",
        "AUTO_DEPLOY_ENABLED",
      ],
      default: "PREPARED",
      index: true,
    },
    setup: {
      repositoryConnected: { type: Boolean, default: false },
      analyzed: { type: Boolean, default: false },
      readinessReported: { type: Boolean, default: false },
      deploymentFilesGenerated: { type: Boolean, default: false },
      dockerHubConnected: { type: Boolean, default: false },
      dockerHubUsername: String,
      ec2Connected: { type: Boolean, default: false },
      ec2Host: String,
      jenkinsConnected: { type: Boolean, default: false },
      jenkinsUrl: String,
      jenkinsUser: String,
      jenkinsPipelineGenerated: { type: Boolean, default: false },
      jenkinsPipelineGeneratedAt: Date,
      jenkinsfilePath: String,
      jenkinsfileContent: String,
      jenkinsfileStack: String,
      cicdGenerated: { type: Boolean, default: false },
      jenkinsJobCreated: { type: Boolean, default: false },
      githubWebhookConfigured: { type: Boolean, default: false },
      githubWebhookConfiguredAt: Date,
      githubWebhookUrl: String,
      githubWebhookHookId: Number,
      autoDeployEnabled: { type: Boolean, default: false },
      autoDeployEnabledAt: Date,
      updatedAt: Date,
    },
    currentBuildId: String,
    currentImageTag: String,
    currentImageId: String,
    autoDeployStatus: {
      type: String,
      enum: [
        "QUEUED",
        "BUILDING",
        "TESTING",
        "PUSHING",
        "DEPLOYING",
        "HEALTH_CHECK",
        "SUCCESS",
        "FAILED",
      ],
      default: "QUEUED",
      index: true,
    },
    jenkins: {
      jobId: String,
      jobName: String,
      jobUrl: String,
      buildNumber: Number,
      buildUrl: String,
      error: mongoose.Schema.Types.Mixed,
    },
    testedAt: Date,
    validation: {
      hasPackageJson: Boolean,
      hasDockerfile: Boolean,
      hasJenkinsfile: Boolean,
      hasDockerCompose: Boolean,
      dockerfileValid: Boolean,
      jenkinsfileValid: Boolean,
      notes: [String],
    },
    version: {
      type: String,
      default: "1.0.0",
    },
    previousVersion: String,
    status: {
      type: String,
      enum: [
        "initializing",
        "pending",
        "running",
        "in-progress",
        "completed",
        "deployed",
        "success",
        "failed",
        "rolled-back",
        "PENDING",
        "PREPARING",
        "READY_FOR_BUILD",
        "FAILED",
      ],
      default: "initializing",
    },
    currentPhase: {
      type: Number,
      default: 1,
    },
    currentStep: String,
    failedStep: String,
    failureStack: String,
    error: String,
    deploymentError: String,
    phaseProgress: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    overallProgress: {
      type: Number,
      default: 0,
    },
    autoDeployEnabled: {
      type: Boolean,
      default: false,
    },
    ec2Instance: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    generatedKeyName: String,
    generatedPrivateKey: String,
    applicationUrl: String,
    repositoryUrl: String,
    repositoryName: String,
    // Deployment endpoint information
    deploymentEndpoint: {
      publicIp: String,
      publicDns: String,
      instanceId: String,
      containerPort: {
        type: Number,
        default: 3000,
      },
      imageName: String,
      healthStatus: {
        type: String,
        enum: ["pending", "checking", "healthy", "unhealthy", "unknown"],
        default: "unknown",
      },
      healthCheckStatus: String,
      lastHealthCheck: Date,
      isLive: {
        type: Boolean,
        default: false,
      },
    },
    stepLogs: [
      {
        timestamp: {
          type: Date,
          default: Date.now,
        },
        step: String,
        level: {
          type: String,
          enum: ["info", "warn", "error", "debug", "success"],
          default: "info",
        },
        event: String,
        input: mongoose.Schema.Types.Mixed,
        output: mongoose.Schema.Types.Mixed,
        error: String,
        errorDetails: mongoose.Schema.Types.Mixed,
        stack: String,
      },
    ],
    environment: {
      type: String,
      enum: ["development", "staging", "production"],
      default: "production",
    },
    containers: [
      {
        name: String,
        image: String,
        status: String,
        ports: [String],
      },
    ],
    deploymentType: {
      type: String,
      enum: ["manual", "auto", "rollback", "workspace-prepare"],
      default: "auto",
    },
    deployedBy: String,
    deploymentScript: String,
    startTime: Date,
    endTime: Date,
    duration: Number,
    rollbackReason: String,
    logs: [
      {
        timestamp: {
          type: Date,
          default: Date.now,
        },
        level: {
          type: String,
          enum: ["info", "warn", "error", "debug", "success"],
          default: "info",
        },
        message: {
          type: String,
          required: true,
        },
      },
    ],
    createdAt: {
      type: Date,
      default: Date.now,
    },
    updatedAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

deploymentSchema.index({ userId: 1, createdAt: -1 });
deploymentSchema.index({ status: 1 });
deploymentSchema.index({ version: 1 });
deploymentSchema.index({ buildNumber: -1 });

export const Deployment = mongoose.model("Deployment", deploymentSchema);
